#!/usr/bin/env ruby
require 'optparse'

options = {}

ARGV << '-h' if ARGV.empty?

OptionParser.new do |opts|
  opts.banner = "Usage: ./quick_script [options]"

  opts.on('-v', '--[no-]verbose', 'Run verbosely') { |v| options[:verbose] = v }

  opts.on('-h', '--help', "Print this help") do
    puts opts
    exit
  end

end.parse!

p options
p ARGV
