#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='mvim -f'
export VISUAL='mvim -f'
export PAGER='less'
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2375

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG="zh_TW.UTF-8"
  export LC_COLLATE="zh_TW.UTF-8"
  export LC_CTYPE="zh_TW.UTF-8"
  export LC_MESSAGES="zh_TW.UTF-8"
  export LC_MONETARY="zh_TW.UTF-8"
  export LC_NUMERIC="zh_TW.UTF-8"
  export LC_TIME="zh_TW.UTF-8"
  export LC_ALL=
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Node path
export NODE_PATH="/usr/local/lib/node_modules"

# GO path
export GOPATH=$HOME/go

# PSQL path
export PQ_PATH='/Applications/Postgres.app/Contents/Versions/9.3/bin'

# Set the list of directories that Zsh searches for programs.
path=(
  ~/.cask/bin
  $GOPATH
  $PQ_PATH
  /usr/local/share/npm/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

