declare -A homebrew_prefix
homebrew_prefix[x86_64]=/usr/local
homebrew_prefix[arm64]=/opt/homebrew

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

export LANG=en_US.UTF-8

# Haskell
export HASKELL_INSTALL_PATH=$HOME/.local/bin
[ -d $HASKELL_INSTALL_PATH ] && export PATH=$PATH:$HASKELL_INSTALL_PATH

# ANDROID
# export ANDROID_HOME=$brew_prefix[$CPUTYPE]/share/android-sdk
# [ -d $ANDROID_HOME ] && export PATH=$PATH:$ANDROID_HOME

 # Nix
 # if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
 #    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
 # fi
 # End Nix

export HOMEBREW_PATH=/opt/homebrew
[ -d $HOMEBREW_PATH ] && eval "$(/opt/homebrew/bin/brew shellenv)"

# Rust
if [ -e 'rustc' ]; then
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

source $HOME/.cargo/env
source "$HOME/.config/rustlang/autocomplete/rustup"

fi

export IDRIS2_PATH=$HOME/.idris2
if [ -d $IDRIS2_PATH ]; then
  export LD_LIBRARY_PATH=$IDRIS2_PATH/lib
  export PATH=$PATH:$IDRIS2_PATH/bin
fi

export DOTNET_TOOLS_PATH=$HOME/.dotnet/tools
[ -d $DOTNET_TOOLS_PATH ] && export PATH=$PATH:$DOTNET_TOOLS_PATH
