#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

# https://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html

if [[ -f ~/.dotfiles/credentials ]]; then
  source ~/.dotfiles/credentials
fi

skip_global_compinit=1

# http://disq.us/p/f55b78
setopt noglobalrcs

# ulimit
ulimit -n 4096

export SYSTEM=$(uname -s)

# Erlang
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export COLORTERM="truecolor"

# GPG
export GPG_TTY=$(tty)

# Homebrew
export HOMEBREW_NO_ANALYTICS=1

# https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zshenv
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
